print("Hello World");
char x = '!';
println(x);
// Using Concatenation
String a = "You"; 
String b = "said"; 
String c = "\tHello!\t   "; 
String d = "to"; 
String e = "me"; 
String f = "."; 
println(a, b, c, d, e + f);
String g = "Tamara";
String h = "Amazing";
String i = "Kaddoura";
String j = "counts";
String k = "to";
String l = "10";
int ten = int(l);
String m = "by";
String n = "1";
println(g, h, i, j, k, l+1, m, n);
println(g, h, i, j, k, ten=1, m, n);
